LIB = 

INCLUDE_DIRS = $(ROOT)/http \
				$(ROOT)/packetfilemgr \
				$(ROOT)/gw

BUILD_DIR = $(BUILDS)/rexmit
LINK_LIBS = http packetfilemgr \
			curl 

EXE = traitsrexmit

include $(ROOT)/make.rule
