LIB = 

INCLUDE_DIRS = $(ROOT)/http \
				$(ROOT)/packetfilemgr \
                $(ROOT)/easylogger \
				$(ROOT)/gw

BUILD_DIR = $(BUILDS)/rexmit
LINK_LIBS = http pfmgr elog\
			curl 

EXE = traitsrexmit

include $(ROOT)/make.rule
