LIB = libpacketfilemgr.a

INCLUDE_DIRS = $(ROOT)/packetfilemgr \
               $(ROOT)/easylogger \
               $(ROOT)/gw
BUILD_DIR = $(BUILDS)/packetfilemgr
LINK_LIBS = 

EXE = 

include $(ROOT)/make.rule

